### ISSUE TITLE
Run tests 

### ISSUE THREAD

**Issue by MaxMcGlinnPoole** [MaxMcGlinnPoole/CMSC441Proj2#5]
This should be run with 1,2,4, and 8 processes at least.

To go above and beyond we can use hpcf2013 to use 16 processes as well.

**Comment by maebig1** [comment]
My int main() runs various sizes of input, we can use that to have one program that captures a full set of data of empirical results.  All I should have to do is make a few edits that writes the info to the screen in  a somewhat formatted way (if its even ugly, I cant remember).  Ill do that before the T1 / Tinf parts
