### ISSUE TITLE
Implement Serial code in C++

### ISSUE THREAD

**Issue by MaxMcGlinnPoole** [MaxMcGlinnPoole/CMSC441Proj2#7]
I have written a non-working version of the code, we can get it working with a little bit of elbow grease.

This is basically converting the python code into C++.

**Comment by MaxMcGlinnPoole** [comment]
max_line_folds function is written. We still need to finish rebuilding the pairs though.

**Comment by maebig1** [comment]
Hey have you tried to use the Maya account?  Or have you used it
before for the parallelism?

On 11/6/16, MaxMcGlinnPoole notifications@github.com wrote:

> max_line_folds function is written. We still need to finish rebuilding the
> pairs though.
> 
> ## 
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/MaxMcGlinnPoole/CMSC441Proj2/issues/7#issuecomment-258717788

## 

V/r,

Michael Aebig

**Comment by maebig1** [comment]
In library rn on the 1st floor
You can txt me also 202 971 5515

From my Phone

**Comment by MaxMcGlinnPoole** [comment]
I have an account, i've used it for all my projects in parallel computing.

**Comment by maebig1** [comment]
I'm going to resolve the Maya accounts issue, mine in on the way

**Comment by maebig1** [comment]
https://www.overleaf.com/6985286hknmwhtjgpmx#/23924356/

https://www.overleaf.com/6910908vfrqfcnjyypv#/23611502/

On 11/6/16, MaxMcGlinnPoole notifications@github.com wrote:

> max_line_folds function is written. We still need to finish rebuilding the
> pairs though.
> 
> ## 
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/MaxMcGlinnPoole/CMSC441Proj2/issues/7#issuecomment-258717788

## 

V/r,

Michael Aebig
